export * from './lib/compareArray'
export * from './lib/compareNumber'
export * from './lib/compareNumberDescending'
export * from './lib/compareNumeric'
export * from './lib/compareNumericDescending'
export * from './lib/compareString'
export * from './lib/compareStringDescending'
export * from './types/Comparator'