export const CLI_LIST = [
  //
  'b',
  'b repo',
  'b git',
  'b find',
  'b gpt',
  'b rman',

  'b find search',
  'b find index',
  //
  'b git commit',
  'b git push',
  'b git checkout',
  'b git branch',

  //
  'b github repo create',
  'b github repo delete',
  'b github repo rename',
  //
  'b git branch list',
  'b git branch create',
  'b git branch delete',
  'b git branch rename',
  'b git branch move',
  'b git branch merge',
  //
  'b uuid generate',
  //
  'b gpt q',
  'b gpt EN',
  'b gpt DK',
  'b gpt refactor',
  'b gpt java',
  'b gpt ub',
  'b gpt ubsw',
  'b gpt ts',
  'b gpt npm',
  'b gpt tsdocf',
  'b gpt tsdocc',
  'b gpt tstest',
  'b gpt preset',
  'b gpt appdata',
  'b gpt config',
  'b gpt all-help',
  //
  'b rman build',
  'b rman test',
  'b rman lint',
  'b rman docs',
  'b rman fix',
  'b rman foreach',
  'b rman dev',
  'b rman precommit',
  'b rman publish',
  'b rman wipe-modules',
  'b rman rehash',
  'b rman runts',
  'b rman testfile',
  'b rman create-package',
  'b rman delete-package',
  'b rman deps',
  'b rman opendocs',
  'b rman opencov',
  'b rman appdata',
  'b rman config',
  'b rman all-help',
].sort()
